### ISSUE TITLE
Tile BG images? 

### ISSUE THREAD

**Issue by jandrew36** [mattohagan/jot#7]
I have a 27 inch monitor and the bg images are always being Tiled. Doesn't look good.

**Comment by sergiopantoja** [comment]
This is happening because the background styling is being applied to the `<html>` element ([here](https://github.com/mattohagan/jot/blob/master/jot/css/main.css#L15)), but JS script is adding the background image to the `<body>` element ([here](https://github.com/mattohagan/jot/blob/master/jot/jot.js#L283)).
